name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: echo "${{ secrets.DOCKER_HUB_KEY }}" | docker login -u ${{ secrets.DOCKER_HUB_NAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag muyiafan/my-php && docker push muyiafan/my-php
